# yaml-language-server: $schema=./src/config/schema.json
project:
  name: emb
  rootDir: examples

## Plugins configs
plugins:
  # Auto-discover components (default: folders with */Dockerfile)
  - name: autodiscover

  # Load some .env files
  - name: dotenv
    config:
      - .env
      - .env.commons

  # Load components' Embfiles
  - name: embfiles

## Add variables to the environment
env:
  DOCKER_TAG: ${env:DOCKER_TAG:-latest}

# Vars, contrary to the 'env' vars
# wont be passed down to subprocesses
vars: {}

# Some default for every docker build
defaults:
  docker:
    tag: ${env:DOCKER_TAG}

# The order is not important
# as we will build a dependency graph
components:
  # The most simple way to add a component
  # This should not be necessary when using autodiscovery
  # This component will assume:
  # - the folder 'simple/' exists
  # - the Dockerfile 'simple/Dockerfile' exists
  - name: simple

## Flavours
flavors:
  - name: production
    env:
      DOCKER_TAG: production
    components:
      - name: frontend
        target: production
