# yaml-language-server: $schema=./src/config/schema.json
project:
  name: emb
  rootDir: examples

# ## Plugins configs
plugins:
  # Auto-discover components (default: folders with */Dockerfile)
  - name: autodocker

  # Load some .env files
  - name: dotenv
    config:
      - .env
      - .env.commons

  # Load components' Embfiles
  - name: embfiles

## Add variables to the environment
env:
  DOCKER_TAG: ${env:DOCKER_TAG:-latest}

# Vars, contrary to the 'env' vars
# wont be passed down to subprocesses
vars: {}

# Some default for every docker build
defaults:
  docker:
    tag: ${env:DOCKER_TAG}

## Tasks
tasks:
  prereq:
    script: | # shell
      echo "I should run before task 'dependent'";
      echo "'prereq' has run" > /tmp/tasks.txt

  dependent:
    pre: ['prereq']
    script: | # shell
      echo I should run after task 'prereq'
      grep 'prereq' /tmp/tasks.txt || (echo "Prereq task has not run" && exit 1)

  greet:
    vars:
      USER: ${env:USER:-world}
    script: | # shell
      echo "Hello $USER!"

flavors:
  production:
    patches:
      - op: replace
        path: /env/DOCKER_TAG
        value: ${env:DOCKER_TAG}-production
