# yaml-language-server: $schema=./src/config/schema.json
project:
  name: emb
  rootDir: examples

# Some default vars available everywhere
vars:
  dockerTag: ${env:DOCKER_TAG:-latest}

# Some default for every docker build
defaults:
  docker:
    tag: ${dockerTag}

# The order is not important
# as we will build a dependency graph
components:
  - simple
  - name: base
  - name: frontend
    tasks:
      - name: test
        executor: shell
        script: | # shell
          ls /tmp | wc -l

  - name: buildargs
    buildArgs:
      # Inject some env var as build arg
      GREETING: Hello ${env:USER}
  - name: dependent
    dependencies:
      - base

flavors:
  production:
    defaults:
      docker:
        tag: production
    components:
      - name: frontend
        target: production
