# yaml-language-server: $schema=./src/config/schema.json
project:
  name: emb
  rootDir: examples

# Some default vars available everywhere
vars:
  dockerTag: ${env:DOCKER_TAG:-latest}

# Some default for every docker build
defaults:
  docker:
    tag: ${dockerTag}

# Overrides per components
components:
  - simple
  - frontend
  # On purpose putting dependent before base
  - name: dependent
    dependencies:
      - base
  - base
  - name: buildargs
    buildArgs:
      # Inject some env var as build arg
      GREETING: Hello ${env:USER}

flavors:
  production:
    defaults:
      docker:
        tag: production
    components:
      - name: frontend
        target: production
