# .gitlab-ci.yml

default:
  image: node:22 # Node + npm available in all jobs

stages:
  - build
  - test

variables:
  NODE_ENV: test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - node -v
  - npm -v
  - npm ci

build:
  stage: build
  tags:
    - docker
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1h

test:
  stage: test
  script:
    - npm run test
