#!/usr/bin/env node
/**
 * Wall-clock ladder for CLI startup, isolating each stage of an `emb` run.
 *
 * Reads as a ladder: each rung adds one layer of work, so the cost of a layer
 * is the gap to the rung below it.
 *
 *   node boot          node process floor
 *   emb --version      + oclif bootstrap
 *   emb tasks          + config load, monorepo init, command module graph
 *   emb ps             + the docker compose subprocess
 *   docker compose ps  what `emb ps` actually wraps — the honest baseline
 *
 * Usage:
 *   scripts/bench-startup.mjs [monorepo-dir] [--batch N] [--batches N]
 *
 * Timing is amortized over a batch rather than measured per run, so the
 * harness costs one pair of timestamps per batch instead of per sample. The
 * median of several batches is reported: single runs on a loaded machine vary
 * by ~20%, so treat differences under ~150ms as noise.
 *
 * Runs against dist/, so run `npm run build` first.
 */
import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const EMB = path.join(REPO_ROOT, 'bin', 'run.js');

// Without a manifest oclif imports every command file at startup just to read
// its metadata, which loads the whole codebase. The published package always
// ships one (generated by `prepack`), so measuring without it compares against
// a configuration no user actually runs.
if (!existsSync(path.join(REPO_ROOT, 'oclif.manifest.json'))) {
  console.error(
    '\n  WARNING: oclif.manifest.json is missing, so these numbers are inflated\n' +
      '  relative to the published package. Run `npx oclif manifest` first.\n' +
      '  (Remember to delete it afterwards — a stale manifest serves outdated\n' +
      '  command metadata during development.)\n',
  );
}

const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = argv.indexOf(`--${name}`);

  return i === -1 ? fallback : Number(argv[i + 1]);
};

const cwd = argv.find((a) => !a.startsWith('--') && !/^\d+$/.test(a)) ?? process.cwd();
const BATCH = flag('batch', 8);
const BATCHES = flag('batches', 3);

const run = (cmd, args) => spawnSync(cmd, args, { cwd, stdio: 'ignore' });

const RUNGS = [
  { label: 'node boot (floor)', cmd: process.execPath, args: ['-e', ''] },
  { label: 'emb --version', cmd: process.execPath, args: [EMB, '--version'] },
  { label: 'emb tasks', cmd: process.execPath, args: [EMB, 'tasks'] },
  { label: 'emb ps', cmd: process.execPath, args: [EMB, 'ps'] },
  { label: 'docker compose ps', cmd: 'docker', args: ['compose', 'ps'] },
];

const median = (xs) => [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)];

console.log(`\ncwd      : ${cwd}`);
console.log(`sampling : median of ${BATCHES} batches x ${BATCH} runs\n`);

for (const { label, cmd, args } of RUNGS) {
  // Warm up: the first runs pay for cold filesystem cache, and can be an order
  // of magnitude slower than steady state.
  run(cmd, args);
  run(cmd, args);

  const timings = [];
  for (let b = 0; b < BATCHES; b++) {
    const start = performance.now();
    for (let i = 0; i < BATCH; i++) {
      run(cmd, args);
    }
    timings.push(Math.round((performance.now() - start) / BATCH));
  }

  console.log(
    `${String(median(timings)).padStart(6)} ms  ${label.padEnd(22)} (batches: ${timings.join(' ')})`,
  );
}

console.log('');
